# Application configuration
spring.application.name=Sellify Api
spring.profiles.active=dev

# JPA configuration
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true

# Server configuration
server.port=8080

# Static resources configuration
spring.web.resources.add-mappings=false

# Internationalization configuration
spring.messages.basename=messages
spring.messages.encoding=UTF-8

# Security configuration
jwt.expiration=3600
jwt.token-name=access_token
jwt.refresh-expiration=604800
jwt.refresh-token-name=refresh_token
jwt.claims.role-id=roleId
jwt.claims.company-id=companyId