# Database configuration postgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/sellify_db
spring.datasource.username=postgres
spring.datasource.password=123456

# Logging configuration
logging.level.org.springframework=INFO
logging.level.com.sellify=DEBUG

# CORS configuration
cors.allowed-origins=http://localhost:4200
cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
cors.allowed-headers=Authorization,Content-Type
cors.allow-credentials=true

# Security configuration
jwt.secret=Y8yF9xHVn7GJj2LmN5E4w0ZsDqXcR6aU1PpS9BKTmO3eWjw
jwt.secure-cookie=false